from pathlib import Path
from typing import Any
import yaml

from context.scripts.generators.adapters.core.models import CanonicalAgent


def _extract_model_mappings(repo_root: Path, provider_name: str) -> str:
    """Extracts model mappings from context/models.yaml for a specific provider."""
    models_yaml_path = repo_root / "context" / "models.yaml"
    if not models_yaml_path.exists():
        return ""
        
    try:
        data = yaml.safe_load(models_yaml_path.read_text())
        tiers = data.get("tiers", {})
        
        mappings = []
        for tier_name, tier_data in tiers.items():
            providers = tier_data.get("providers", {})
            provider = providers.get(provider_name)
            if provider:
                alias = provider.get("runtime_alias", "unknown")
                mappings.append(f"- `{tier_name}` -> `{alias}`")
                
        if mappings:
            return "\n".join(mappings)
    except Exception:
        pass
        
    return ""


def generate_claude_md(context: dict[str, Any], output_dir: Path) -> None:
    """Generates the repository-level CLAUDE.md file."""
    claude_md_path = output_dir / "CLAUDE.md"
    
    model_mappings = _extract_model_mappings(output_dir, "anthropic")
    
    content = (
        "# Claude System Instructions\n\n"
        "**Auto-generated by context/scripts/generators/generate_adapters.py — do not edit manually**\n\n"
        "Please read and strictly adhere to the instructions, standards, and workflows defined in `@AGENTS.md`.\n\n"
        "## Tool Mappings\n"
        "- Use `Bash` or `Command` for executing terminal commands.\n"
        "- Use `Replace` for editing files.\n"
        "- Use `Glob` for file searching.\n\n"
        "## Model Mappings\n"
        f"{model_mappings}\n\n"
        "## Subagent Spawning\n"
        "To invoke a specific agent for a task, you must read its prompt: `@.claude/prompts/{agent_name}.md`\n"
    )
    
    claude_md_path.write_text(content)


def generate_subagent_prompts(context: dict[str, Any], output_dir: Path) -> None:
    """Generates standalone agent prompts for Claude Code."""
    agents: dict[str, CanonicalAgent] = context.get("agents", {})
    prompts_dir = output_dir / ".claude" / "prompts"
    prompts_dir.mkdir(parents=True, exist_ok=True)
    
    for agent_name, agent in agents.items():
        prompt_path = prompts_dir / f"{agent_name}.md"
        content = (
            f"# {agent.name.replace('-', ' ').title()}\n\n"
            "**Auto-generated by context/scripts/generators/generate_adapters.py — do not edit manually**\n\n"
            f"## Description\n{agent.description}\n\n"
        )
        if agent.standards:
            content += "## Standards\n"
            for std in agent.standards:
                content += f"- @context/standards/{std}\n"
            content += "\n"
            
        if agent.rules:
            content += "## Rules\n"
            for rule in agent.rules:
                content += f"- @context/rules/{rule}\n"
            content += "\n"
            
        prompt_path.write_text(content)
