import os
from pathlib import Path
from typing import Any

from context.scripts.generators.adapters.core.models import CanonicalAgent


def generate_skills(context: dict[str, Any], output_dir: Path, dry_run: bool = False) -> dict[Path, str]:
    """
    Translates canonical agents into Antigravity SKILL.md files.
    """
    agents: dict[str, CanonicalAgent] = context.get("agents", {})
    skills_dir = output_dir / ".agents" / "skills"
    
    results: dict[Path, str] = {}
    
    for agent_name, agent in agents.items():
        agent_dir = skills_dir / agent_name
        skill_md_path = agent_dir / "SKILL.md"
        content = (
            "---\n"
            f"name: {agent.name}\n"
            f"description: {agent.description}\n"
            "---\n\n"
            f"# {agent.name.replace('-', ' ').title()}\n\n"
            "**Auto-generated by context/scripts/generators/generate_adapters.py — do not edit manually**\n\n"
            f"## Description\n{agent.description}\n\n"
        )
        if agent.standards:
            content += "## Standards\n"
            for std in agent.standards:
                content += f"- {std}\n"
            content += "\n"
        
        if agent.rules:
            content += "## Rules\n"
            for rule in agent.rules:
                content += f"- {rule}\n"
            content += "\n"
            
        results[skill_md_path] = content
        if not dry_run:
            agent_dir.mkdir(parents=True, exist_ok=True)
            skill_md_path.write_text(content)
            
    return results


import yaml

def _extract_model_mappings(repo_root: Path, provider_name: str) -> str:
    """Extracts model mappings from context/models.yaml for a specific provider."""
    models_yaml_path = repo_root / "context" / "models.yaml"
    if not models_yaml_path.exists():
        return ""
        
    try:
        data = yaml.safe_load(models_yaml_path.read_text())
        tiers = data.get("tiers", {})
        
        mappings = []
        for tier_name, tier_data in tiers.items():
            providers = tier_data.get("providers", {})
            provider = providers.get(provider_name)
            if provider:
                alias = provider.get("runtime_alias", "unknown")
                mappings.append(f"- `{tier_name}` -> `{alias}`")
                
        if mappings:
            return "\n".join(mappings)
    except Exception:
        pass
        
    return ""


def generate_gemini_md(context: dict[str, Any], output_dir: Path, dry_run: bool = False) -> dict[Path, str]:
    """
    Generates the repository-level GEMINI.md file.
    """
    gemini_md_path = output_dir / "GEMINI.md"
    
    model_mappings = _extract_model_mappings(output_dir, "google")
    
    content = (
        "# Antigravity System Instructions\n\n"
        "**Auto-generated by context/scripts/generators/generate_adapters.py — do not edit manually**\n\n"
        "Please read and strictly adhere to the instructions, standards, and workflows defined in `@AGENTS.md`.\n\n"
        "## Tool Mappings\n"
        "- Use `replace_file_content` for editing contiguous blocks of code.\n"
        "- Use `run_command` for executing terminal commands.\n"
        "- Use `call_mcp_tool` for MCP interactions.\n\n"
        "## Model Mappings\n"
        f"{model_mappings}\n"
    )
    
    if not dry_run:
        gemini_md_path.write_text(content)
        
    return {gemini_md_path: content}
