from pathlib import Path
from typing import Any

from context.scripts.generators.adapters.core.models import CanonicalAgent, WorkflowDAG


def _trim_purpose(text: str) -> str:
    """Extract core purpose: first sentence, parentheticals removed."""
    import re
    idx = text.find('.')
    sentence = text[:idx].strip() if idx != -1 else text.strip()
    return re.sub(r'\s*\([^)]*\)', '', sentence).strip()


def generate_workflow_table(workflows: dict[str, WorkflowDAG]) -> str:
    """Generate workflow index table."""
    rows = [
        "| Workflow | Purpose |",
        "|----------|---------|",
    ]
    for name, data in sorted(workflows.items()):
        desc = _trim_purpose(data.description)
        rows.append(f"| `{name}` | {desc} |")
    return '\n'.join(rows)


def generate_agent_dispatch_all(agents: dict[str, CanonicalAgent]) -> str:
    """Render agent dispatch table."""
    category_order = [
        'product-owner', 'product-expert',
        'solution-architect', 'database-designer', 'api-designer', 'ui-designer',
        'functional-tester', 'python-coder', 'typescript-coder',
        'tech-lead', 'code-reviewer', 'principles-reviewer',
        'ui-tester', 'security-tester',
        'devops', 'gcp-devops',
        'documentation',
        'workflow-analyst',
        'tokenomics-analyst',
    ]
    
    # Sort by predefined order, then alphabetically for the rest
    ordered = [a for a in category_order if a in agents]
    remainder = sorted(set(agents.keys()) - set(ordered))
    all_agent_names = ordered + remainder
    
    rows = [
        "| Agent | Purpose |",
        "|-------|---------|",
    ]
    for agent_name in all_agent_names:
        agent_data = agents[agent_name]
        purpose = _trim_purpose(agent_data.description)
        rows.append(f"| `@{agent_name}` | {purpose} |")
    return '\n'.join(rows)


def generate_agents_md(context: dict[str, Any], output_dir: Path, dry_run: bool = False) -> dict[Path, str]:
    """Generates the unified AGENTS.md orchestrator file."""
    agents = context.get("agents", {})
    workflows = context.get("workflows", {})
    
    agents_path = output_dir / "AGENTS.md"
    
    content = f"""# AGENTS.md

## System Instructions
Always follow the specific instructions in the `context/` directory.

## Standards
INLINE_COMPREHENSIVE

## Tool Mappings
- Use `replace_file_content` for editing contiguous blocks of code.
- Use `run_command` for executing terminal commands.
- Use `call_mcp_tool` for MCP interactions.

## On Start
Glob `**/artefacts/README.md` and read all matches. Run `git log --oneline -5`.
Read `@context/agents/orchestrator.md`.
Read `artefacts/build/HANDOFF.md` if it exists — the `Workflow:` field identifies the active workflow.
Load `@context/workflows/<workflow>.yaml`. If no HANDOFF.md exists, ask the user which workflow to start.

## Workflows

{generate_workflow_table(workflows)}

## Agents

{generate_agent_dispatch_all(agents)}

**Spawn**: `"Read @context/agents/{{name}}.md before starting. [task]"`

_Auto-generated by context/scripts/generators/generate_adapters.py — do not edit manually_
"""
    if not dry_run:
        agents_path.write_text(content)
    return {agents_path: content}
