# /// script
# dependencies = [
#   "pyyaml",
# ]
# ///
#!/usr/bin/env python3
from __future__ import annotations

"""Pre-commit validator: detects desynchronisation between canonical context/ and adapter projections.

Compares on-disk adapter projections against fresh in-memory generation output.
Fails with exit code 1 if any generated file is missing, modified, or out of date.
"""

import argparse
import sys
from pathlib import Path

# Ensure repository root is on sys.path
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from context.scripts.generators.adapters.core.loader import load_canonical_context
from context.scripts.generators.generate_adapters import get_adapter_projections


def check_adapter_drift(
    repo_root: Path | None = None,
    context_dir: Path | None = None,
    targets: set[str] | None = None,
) -> tuple[bool, list[str]]:
    """Checks for drift between expected in-memory projections and files on disk.

    Args:
        repo_root: Repository root directory (default: auto-detected).
        context_dir: Context directory containing canonical YAML/markdown files.
        targets: Target runtimes to check (default: all).

    Returns:
        Tuple of (is_synced: bool, drift_details: list[str]).
    """
    if repo_root is None:
        if (Path.cwd() / "context").is_dir():
            repo_root = Path.cwd()
        else:
            repo_root = Path(__file__).resolve().parent.parent.parent.parent
    if context_dir is None:
        context_dir = repo_root / "context"

    context = load_canonical_context(str(context_dir))
    expected_projections = get_adapter_projections(context, repo_root, targets)

    drift_issues: list[str] = []

    # 1. Check all expected projections exist and match content on disk
    for path, expected_content in sorted(expected_projections.items()):
        rel_path = path.relative_to(repo_root) if path.is_relative_to(repo_root) else path

        if not path.exists():
            drift_issues.append(f"MISSING: {rel_path} does not exist on disk.")
        else:
            disk_content = path.read_text()
            if disk_content != expected_content:
                drift_issues.append(
                    f"MODIFIED: {rel_path} content does not match canonical context projection."
                )

    # 2. Check for orphaned files in managed generation directories
    managed_dirs = [
        repo_root / ".agents" / "skills",
        repo_root / ".claude" / "prompts",
        repo_root / ".github" / "prompts",
        repo_root / ".github" / "instructions",
        repo_root / ".openai" / "prompts",
    ]

    expected_paths_set = set(expected_projections.keys())
    for d in managed_dirs:
        if not d.exists():
            continue
        for f in d.rglob("*"):
            if f.is_file():
                # Only check files that contain our auto-generated marker
                try:
                    content = f.read_text()
                    if "Auto-generated by context/scripts/generators/generate_adapters.py" in content:
                        if f not in expected_paths_set:
                            rel_f = f.relative_to(repo_root) if f.is_relative_to(repo_root) else f
                            drift_issues.append(
                                f"ORPHANED: {rel_f} exists on disk but is no longer generated from canonical context."
                            )
                except Exception:
                    pass

    is_synced = len(drift_issues) == 0
    return is_synced, drift_issues


def main() -> None:
    """CLI entry point for adapter drift validator."""
    parser = argparse.ArgumentParser(
        prog="agent-drift",
        description="Verify that runtime adapter projections are strictly synchronized with context/ definitions.",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Repository root path (default: auto-detected).",
    )
    parser.add_argument(
        "--context-dir",
        type=Path,
        default=None,
        help="Context directory path (default: <repo-root>/context).",
    )
    parser.add_argument(
        "-t",
        "--target",
        metavar="TARGET",
        help="Specific target runtime to check (default: all).",
    )
    args = parser.parse_args()

    targets = {args.target.lower()} if args.target else None

    is_synced, drift_issues = check_adapter_drift(
        repo_root=args.repo_root,
        context_dir=args.context_dir,
        targets=targets,
    )

    if is_synced:
        print("✅ All runtime adapter projections are in sync with context/.")
        sys.exit(0)
    else:
        print("❌ Runtime adapter drift detected! The following projections are out of sync:\n")
        for issue in drift_issues:
            print(f"  • {issue}")
        print("\nFix: run the adapter generator to synchronize projections:")
        print("  python context/scripts/generators/generate_adapters.py\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
