import re
from pathlib import Path
from typing import Any

from context.scripts.generators.adapters.core.models import CanonicalAgent


def generate_prompts(context: dict[str, Any], output_dir: Path) -> None:
    """Translates canonical agents into GitHub Copilot custom prompt files."""
    agents: dict[str, CanonicalAgent] = context.get("agents", {})
    prompts_dir = output_dir / ".github" / "prompts"
    prompts_dir.mkdir(parents=True, exist_ok=True)
    
    for agent_name, agent in agents.items():
        prompt_path = prompts_dir / f"{agent_name}.prompt.md"
        content = (
            f"# {agent.name.replace('-', ' ').title()}\n\n"
            "**Auto-generated by context/scripts/generators/generate_adapters.py — do not edit manually**\n\n"
            f"## Description\n{agent.description}\n\n"
        )
        if agent.standards:
            content += "## Standards\n"
            for std in agent.standards:
                content += f"- @context/standards/{std}\n"
            content += "\n"
            
        if agent.rules:
            content += "## Rules\n"
            for rule in agent.rules:
                content += f"- @context/rules/{rule}\n"
            content += "\n"
            
        prompt_path.write_text(content)


def generate_copilot_instructions(context: dict[str, Any], output_dir: Path) -> None:
    """Generates the repository-level .github/copilot-instructions.md file."""
    copilot_instructions_path = output_dir / ".github" / "copilot-instructions.md"
    copilot_instructions_path.parent.mkdir(parents=True, exist_ok=True)
    
    content = (
        "# GitHub Copilot Instructions\n\n"
        "**Auto-generated by context/scripts/generators/generate_adapters.py — do not edit manually**\n\n"
        "## General Rules\n"
        "- Use British English spelling (e.g. colour, categorise, cancelling).\n"
        "- Follow EARS notation for requirements.\n"
        "- Adhere to LESS Engineering Principles (Lean, Ethical, Scalable, Sustainable).\n"
    )
    
    copilot_instructions_path.write_text(content)


def generate_scoped_instructions(output_dir: Path) -> None:
    """Scans standards for applyTo blocks and generates scoped .instructions.md files."""
    standards_dir = output_dir / "context" / "standards"
    instructions_dir = output_dir / ".github" / "instructions"
    instructions_dir.mkdir(parents=True, exist_ok=True)
    
    for standard_file in standards_dir.glob('*.md'):
        lines = standard_file.read_text().splitlines()
        i = 0
        while i < len(lines):
            line = lines[i]
            if line.startswith('#'):
                if i + 1 < len(lines) and lines[i+1].startswith('<!-- applyTo:'):
                    header_level = len(line) - len(line.lstrip('#'))
                    title = line.lstrip('#').strip()
                    apply_to_match = re.search(r'<!-- applyTo:\s*"(.*?)"\s*-->', lines[i+1])
                    if apply_to_match:
                        apply_to = apply_to_match.group(1)
                        
                        content_lines = []
                        j = i + 2
                        while j < len(lines):
                            if lines[j].startswith('#'):
                                curr_level = len(lines[j]) - len(lines[j].lstrip('#'))
                                if curr_level <= header_level:
                                    break
                            content_lines.append(lines[j])
                            j += 1
                        
                        content = "\n".join(content_lines).strip()
                        
                        filename = title.lower().replace(' ', '-')
                        filename = re.sub(r'[^a-z0-9-]', '', filename)
                        
                        if filename:
                            instr_file = instructions_dir / f"{standard_file.stem}-{filename}.instructions.md"
                            instr_content = (
                                "---\n"
                                f'applyTo: "{apply_to}"\n'
                                "---\n"
                                f"# {title}\n\n"
                                "**Auto-generated by context/scripts/generators/generate_adapters.py — do not edit manually**\n\n"
                                f"{content}\n"
                            )
                            instr_file.write_text(instr_content)
                        
                        i = j - 1
            i += 1
