import shutil
from pathlib import Path
import pytest

from context.scripts.validators.adapter_drift import check_adapter_drift


def test_adapter_drift_clean_repo():
    """Verify that current repository in clean state has zero adapter drift."""
    repo_root = Path(__file__).resolve().parent.parent.parent.parent
    is_synced, drift_issues = check_adapter_drift(repo_root=repo_root)
    assert is_synced, f"Expected no drift, but found: {drift_issues}"
    assert len(drift_issues) == 0


def test_adapter_drift_detects_modified_file(tmp_path: Path):
    """Verify drift detection when a generated file is modified."""
    repo_root = Path(__file__).resolve().parent.parent.parent.parent
    context_dir = repo_root / "context"
    
    # Create a shadow environment in tmp_path
    shutil.copytree(context_dir, tmp_path / "context")
    
    # Run generator in tmp_path to create fresh baseline
    from context.scripts.generators.generate_adapters import run_generation
    run_generation(repo_root=tmp_path, context_dir=tmp_path / "context", targets={"claude"})
    
    # Mutate CLAUDE.md
    claude_md = tmp_path / "CLAUDE.md"
    claude_md.write_text("Corrupted content that causes drift")
    
    is_synced, drift_issues = check_adapter_drift(
        repo_root=tmp_path,
        context_dir=tmp_path / "context",
        targets={"claude"},
    )
    
    assert not is_synced
    assert any("MODIFIED" in issue and "CLAUDE.md" in issue for issue in drift_issues)


def test_adapter_drift_detects_missing_file(tmp_path: Path):
    """Verify drift detection when an expected generated file is missing."""
    repo_root = Path(__file__).resolve().parent.parent.parent.parent
    context_dir = repo_root / "context"
    
    shutil.copytree(context_dir, tmp_path / "context")
    
    from context.scripts.generators.generate_adapters import run_generation
    run_generation(repo_root=tmp_path, context_dir=tmp_path / "context", targets={"claude"})
    
    # Delete CLAUDE.md
    claude_md = tmp_path / "CLAUDE.md"
    claude_md.unlink()
    
    is_synced, drift_issues = check_adapter_drift(
        repo_root=tmp_path,
        context_dir=tmp_path / "context",
        targets={"claude"},
    )
    
    assert not is_synced
    assert any("MISSING" in issue and "CLAUDE.md" in issue for issue in drift_issues)


def test_adapter_drift_detects_orphaned_file(tmp_path: Path):
    """Verify drift detection when an unmanaged auto-generated file exists."""
    repo_root = Path(__file__).resolve().parent.parent.parent.parent
    context_dir = repo_root / "context"
    
    shutil.copytree(context_dir, tmp_path / "context")
    
    from context.scripts.generators.generate_adapters import run_generation
    run_generation(repo_root=tmp_path, context_dir=tmp_path / "context", targets={"claude"})
    
    # Add orphaned prompt
    orphaned_prompt = tmp_path / ".claude" / "prompts" / "deprecated-agent.md"
    orphaned_prompt.write_text(
        "# Deprecated\n\n"
        "**Auto-generated by context/scripts/generators/generate_adapters.py — do not edit manually**\n"
    )
    
    is_synced, drift_issues = check_adapter_drift(
        repo_root=tmp_path,
        context_dir=tmp_path / "context",
        targets={"claude"},
    )
    
    assert not is_synced
    assert any("ORPHANED" in issue and "deprecated-agent.md" in issue for issue in drift_issues)
